export const WORKSPACE_GUIDE_FILE = "GUIDE.md";
export const LEGACY_WORKSPACE_GUIDE_FILE = "CLAUDE.md";

export const WORKSPACE_CONFIG_DIR = ".novel-guide";
export const LEGACY_WORKSPACE_CONFIG_DIR = ".claude";

export const WORKSPACE_AGENTS_DIR = `${WORKSPACE_CONFIG_DIR}/agents`;
export const WORKSPACE_SKILLS_DIR = `${WORKSPACE_CONFIG_DIR}/skills`;
export const WORKSPACE_OUTPUT_STYLES_DIR = `${WORKSPACE_CONFIG_DIR}/output-styles`;

export const LEGACY_WORKSPACE_AGENTS_DIR = `${LEGACY_WORKSPACE_CONFIG_DIR}/agents`;
export const LEGACY_WORKSPACE_SKILLS_DIR = `${LEGACY_WORKSPACE_CONFIG_DIR}/skills`;

export const WORKSPACE_GUIDE_FILES = [
  WORKSPACE_GUIDE_FILE,
  LEGACY_WORKSPACE_GUIDE_FILE,
] as const;

export const WORKSPACE_AGENT_DIRS = [
  WORKSPACE_AGENTS_DIR,
  LEGACY_WORKSPACE_AGENTS_DIR,
] as const;

export const WORKSPACE_SKILL_DIRS = [
  WORKSPACE_SKILLS_DIR,
  LEGACY_WORKSPACE_SKILLS_DIR,
] as const;
